### ISSUE TITLE
get str representation of complex types

### ISSUE THREAD

**Issue by vb-quaestio** [benfred/py-spy#469]
Hi,
when using `dump` subcommand, under the `Arguments` and `Locals` section, for complex types i can see the class and the memory address, eg:

```
        Locals:
            obj: None
            abc: <Series at 0x7f996f45eba8>
            xyz: <DataFrame at 0x7f996f456940>
```

It's doable to view the string representation of this complex objects?
Thanks.
